apiVersion: v1
kind: Service
metadata:
  name: microservice-app1-service
  labels:
    app: microservice-app1
spec:
  selector:
    app: microservice-app1
    tier: web
  ports:
  - port: 80
    targetPort: 6000
  type: LoadBalancer